### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by pandawynn** [PhoebusSi/VQA-VS#1]
Thank you for your great work! I'd like to replicate the experiments on my local machine; would you mind sharing the codes for all of the base models in Table 1? i.e., S-MRL, UpDn, and BAN.

**Comment by PhoebusSi** [comment]
Hi! Sorry for my late response. 
The codes for **LMH** and **UpDn** are modified from [https://github.com/chrisc36/bottom-up-attention-vqa], codes for **S-MRL** and **RUBi** are  modified from [https://github.com/cdancette/rubi.bootstrap.pytorch], codes for **BAN** and **LPF** are modified from [https://github.com/jokieleung/LPF-VQA].
